// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klsuunzaybkjdswzezbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtsc3V1bnpheWJramRzd3plemJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MzU1NDksImV4cCI6MjA2OTUxMTU0OX0.R8GHMj0FTwtsiGfd1cB6IgigXjQePwZK9Fm54nOGMMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});